language: node_js
node_js:
  - "8.13.0"
  - "8.14.0"
  - "10.15.0"
  - "10.16.0"
services:
  - postgresql
addons:
  postgresql: "9.6"
if: branch IN (master, develop)
install:
  - psql -c 'create database local;' -U postgres
  - sed -i '/^PG_CONNECTION_STRING/d' .test.env
  - echo 'PG_CONNECTION_STRING=postgres://postgres:@localhost:5432/local' >> .test.env
  - cp .test.env .env
  - npm i
script:
  - npm test -- --detectOpenHandles
  - npm run upload-coverage
